using WINBIO_SESSION_HANDLE = System.UInt32;

namespace WinBiometricDotNet
{

    /// <summary>
    /// Represent the session handle that connects to a biometric service provider and one or more biometric units.
    /// </summary>
    public sealed class Session
    {

        #region Constructors

        internal Session(WINBIO_SESSION_HANDLE handle, bool asynchronous)
        {
            this.Handle = handle;
            this.IsAsynchronous = asynchronous;
        }

        #endregion

        #region Properties

        /// <summary>
        /// Get the pointer to the session handle.
        /// </summary>
        public WINBIO_SESSION_HANDLE Handle
        {
            get;
        }

        /// <summary>
        /// Gets a value indicating whether the session handle was generated by asynchronous function.
        /// </summary>
        public bool IsAsynchronous
        {
            get;
        }

        #endregion

    }

}